import dash_core_components as dcc
import dash_html_components as html
import dash_daq as daq
import dash_bootstrap_components as dbc
import dash_table
from constants import parameters_name

page_1_layout = html.Div(
    className='main_container',
    children=[
        html.Div(id='fourcolumnsdivusercontrols', className='four-columns-div-user-controls',
                 children=[
                     html.Div([html.Div([daq.PowerButton(id='my-toggle-switch',
                                               label={'label': 'Open page',
                                                      'style': {'fontSize': '22px', 'fontWeight': 'bold',},},
                                               labelPosition='bottom', on=False, size=100, color='green',style = {'marginTop':'1rem'},
                                               className='dark-theme-control'),]),
                               html.Div([html.Div([html.Div([html.I(className="fas fa-home"), ]),
                                                                    dcc.Link('Home', href='/', id='link1')],
                                                                   className='icon_position1'),
                                                          html.Div([html.Div([html.I(className="fas fa-database"), ]),
                                                                    dcc.Link('Database', href='/Database', id='link2')],
                                                                   className='icon_position1'),
                                                        html.Div([html.Div([html.I(className="fas fa-server"), ]),
                                                                     dcc.Link('Enerbat', href='/realTime_Enerbat', id='link3')],
                                                                   className='icon_position1'),
                                                          html.Div([html.Div([html.I(className="fas fa-chart-line"), ]),
                                                                    dcc.Link('RCC/KN', href='/RCC_KN',
                                                                             id='link4')], className='icon_position1'),
                                         ], style = {'margin' : '2rem 2rem 0 2rem'},className='abpage1'),
                               ], className='abpower'),
                     html.Div(
                         dcc.Upload(
                             id='upload-data',
                             children=html.Div([
                                 'Drag and Drop or ',
                                 html.A('Select Files for work')
                             ]),
                             style={
                                 'marginLeft': '-2rem',
                                 'visibility': 'hidden',
                             },
                             # Allow multiple files to be uploaded
                             multiple=True,
                         ),
                     ),
                     html.Div(id="openOPCDiv", children=[], style={'visibility': 'hidden'}),
                     html.Div(className='userControlDownSide',
                              children=[
                                  html.Div(className='userControlDownLeftSide',
                                           children=[
                                                html.Div(id="opcLoad",
                                                        className='div-for-dropdown',
                                                        children=[], ),
                                                html.Div(dcc.Interval(
                                                   id='interval',
                                                   interval=5000,
                                                   n_intervals=3,
                                               )),
                                                html.Div(id='pointLeftFirst', children=[], style={'display': 'None'}),
                                                html.Div(id='pointLeftSecond', children=[], style={'display': 'None'}),
                                                html.Div(id='pointRightFirst', children=[], style={'display': 'None'}),
                                                html.Div(id='pointRightSecond', children=[], style={'display': 'None'}),
                                                html.Div(id='pointLeftFirstTab4', children=[],style={'display': 'None'}),
                                                html.Div(id='pointLeftSecondTab4', children=[],style={'display': 'None'}),
                                                html.Div(id='pointRightFirstTab4', children=[],style={'display': 'None'}),
                                                html.Div(id='pointRightSecondTab4', children=[],style={'display': 'None'}),
                                                html.Div(id='leftSideChecklistValue', children=[],style={'display': 'None'}),
                                                html.Div(id='leftSidedroptValue', children=[],style={'display': 'None'}),
                                                html.Div(id='leftSideChecklistValueHidden', children=[],style={'display': 'None'}),
                                                html.Div(id='leftSideChecklistValueHiddendb', children=[],style={'display': 'None'}),
                                                html.Div(id='deletedval', children=[], style={'display': 'None'}),
                                                html.Div(id='deletedvalref', children=[], style={'display': 'None'}),
                                                html.Div(id='leftSideChecklistValueHiddenTab4', children=[],style={'display': 'None'}),
                                                html.Div(id='tab2hiddenValuex_axis', style={'display': 'None'},children=[]),
                                                html.Div(id='tab2hiddenValuey_axis', style={'display': 'None'}, children=[]),
                                                html.Div(id='tab4hiddenValuex_axissecond', style={'display': 'None'},children=[]),
                                                html.Div(id='tab4hiddenValuey_axissecond', style={'display': 'None'},children=[]),
                                                html.Div(id='tab4hiddenValuex_axis', style={'display': 'None'},children=[]),
                                                html.Div(id='hiddenTextHeader', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTextNote', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTextxaxis', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTextyaxis', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTexty1axis', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTexty2axis', children=[], style={'display': 'None'}),
                                                html.Div(id='selectyaxishidden', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTextHeader4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTextNote4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTextxaxis4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTextyaxis4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenShapeVal', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTexty1axis4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenTexty2axis4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenShapeVal', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenShapeVal', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenShapeDate', children=[],style={'display': 'None'}), ], ),
                                                html.Div(id='hiddenDifferance', children=[], style={'display': 'None'}),
                                                dcc.Store(id='datastore'),
                                                html.Div(id='retrieve', children=[], style={'display': 'None'}),
                                                html.Div(id='datatablehidden', children=[], style={'display': 'None'}),
                                                html.Div(id='radiographhidden', children=[], style={'display': 'None'}),
                                                html.Div(id='sliderHeightTab1hidden', children=[], style={'display': 'None'}),
                                                html.Div(id='sliderWidthTab1hidden', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenShapeValtab4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenShapeDatetab4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenDifferancetab4', children=[], style={'display': 'None'}),
                                                html.Div(id='retrievetab4', children=[], style={'display': 'None'}),
                                                html.Div(id='datatablehiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='radiographhiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='sliderHeightTab1hiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='sliderWidthTab1hiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='minimumValueGraphhiddenfirst', children=[], style={'display': 'None'}),
                                                html.Div(id='minimumValueGraphhiddensecond', children=[], style={'display': 'None'}),
                                                html.Div(id='firstchoosenvalhidden', children=[], style={'display': 'None'}),
                                                html.Div(id='secondchoosenvalhidden', children=[], style={'display': 'None'}),
                                                html.Div(id='leftintegralfirsthidden', children=[], style={'display': 'None'}),
                                                html.Div(id='leftintegralsecondhidden', children=[], style={'display': 'None'}),
                                                html.Div(id='rightintegralfirsthidden', children=[], style={'display': 'None'}),
                                                html.Div(id='rightintegralsecondhidden', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddencharactere', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenvaluechange', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddencleanshape', children=[], style={'display': 'None'}),
                                                html.Div(id='firstchoosenvalhiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='secondchoosenvalhiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='leftintegralfirsthiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='leftintegralsecondhiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='rightintegralfirsthiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='rightintegralsecondhiddentab4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenchoosenChecklistLeft', children=[], style={'display': 'None'}),
                                                html.Div(id='writeexcelhidden', children=[], style={'display': 'None'}),
                                                html.Div(id='writeexcelhiddenTab4', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenrecord1', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenrecord2', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenrecord3', children=[], style={'display': 'None'}),
                                                html.Div(id='hiddenrecord4', children=[], style={'display': 'None'}),
                                                html.Div(id='inputRightY_axishidden', children=[], style={'display': 'None'}),
                                                html.Div(id='inputRightX_axishidden', children=[], style={'display': 'None'}),
                                                html.Div(id='inputRightY_axishdn', children=[], style={'display': 'None'}),
                                                html.Div(id='inputRightX_axishdn', children=[], style={'display': 'None'}),
                                                html.Div(id='checklistvaleurhidden', children=[], style={'display': 'None'}),
                                                html.Div(id='checklistvaleurhidden2', children=[], style={'display': 'None'}),
                                                html.Div(id='shiftaxisdrophidden', children=[], style={'display': 'None'}),
                                                html.Div(id='shift_x_axishidden', children=[], style={'display': 'None'}),
                                                html.Div(id='shift_y_axishidden', children=[], style={'display': 'None'}),
                                                html.Div(id='tab1sendhidden', children=[], style={'display': 'None'}),
                                                html.Div(id='shiftaxisdroptab4hidden', children=[], style={'display': 'None'}),
                                                html.Div(id='shift_x_axistab4hidden', children=[], style={'display': 'None'}),
                                                html.Div(id='shift_y_axistab4hidden', children=[], style={'display': 'None'}),
                                                html.Div(id='output_s', children=[], style={'display': 'None'}),
                                                html.Div(id='radiographtab4hidden', children=[], style={'display': 'None'}),
                                                html.Div(id='reelhidden11', children=[], style={'display': 'None'}),
                                                html.Div(id='reelhidden12', children=[], style={'display': 'None'}),
                                                html.Div(id='reelhidden13', children=[], style={'display': 'None'}),
                                                html.Div(id='reelhidden14', children=[], style={'display': 'None'}),
                                                html.Div(id='reelhidden15', children=[], style={'display': 'None'}),
                                                html.Div(dcc.Graph(id='graphhidden',
                                                     config={'displaylogo': False},
                                                     style={'display': 'None'},
                                                     figure={
                                                         'layout': {'legend': {'tracegroupgap': 0},}
                                                            }
                                                     ), ),
                              ]),]),
        html.Div(id='eightcolumnsdivforcharts', className='eight-columns-div-for-charts',
                 children=[
                     html.Div(
                         className='right-upper',
                         children=[
                             html.Div([
                                 dcc.Tabs(
                                     id="tabs-with-classes",
                                     value='tab-1',
                                     parent_className='custom-tabs',
                                     className='custom-tabs-container',
                                     children=[
                                         dcc.Tab(
                                             id="tab1",
                                             label='Work on unique parameter',
                                             value='tab-1',
                                             className='custom-tab',
                                             selected_className='custom-tab--selected',
                                             children=[],
                                         ),
                                         dcc.Tab(
                                             id="tab4",
                                             label='Work on Different Parameters',
                                             value='tab-4',
                                             className='custom-tab',
                                             # style={'visibility': 'hidden'},
                                             selected_className='custom-tab--selected'
                                         ),
                                         dcc.Tab(
                                             id="tab5",
                                             label='Tab for one option',
                                             value='tab-5',
                                             className='custom-tab',
                                             style={'visibility': 'hidden'},
                                             selected_className='custom-tab--selected'
                                         ),
                                     ]),
                                 html.Div(id='tabs-content-classes'),

                             ]),

                         ]),

                 ]
                 ),
    ]),

page_2_layout = html.Div(
                    [html.Div(
                        [html.Div([
                                 html.Div([html.Div([html.Div([html.I(className="fas fa-home"), ]),
                                                                    dcc.Link('Home', href='/', id='link1')],
                                                                   className='icon_position'),
                                                          html.Div([html.Div([html.I(className="far fa-file-excel"), ]),
                                                                    dcc.Link('Analysis', href='/File', id='link5')],
                                                                   className='icon_position'),
                                                          html.Div([html.Div([html.I(className="fas fa-server"), ]),
                                                                     dcc.Link('Enerbat', href='/realTime_Enerbat', id='link3')],
                                                                   className='icon_position'),
                                                          html.Div([html.Div([html.I(className="fas fa-chart-line"), ]),
                                                                    dcc.Link('RCC/KN', href='/RCC_KN',
                                                                             id='link4')], className='icon_position'),
                                           ],
                                           style = {'margin':'-3rem 0 1rem 0'},className='abpage2'),
                                        dbc.ButtonGroup([dbc.Button("Database Activate", id="activatedb", n_clicks=0,
                                                     size="lg", className='mr-1', color="success",
                                                     style={'width': '25rem', 'marginBottom' : '1rem','borderRadius' : '2rem'}
                                                     ),
                                                     dbc.Button("Database Deactivate", id="deactivatedb", n_clicks=0,
                                                             size="lg", className='mr-1', color="danger",
                                                             style={'width': '25rem', 'marginBottom' : '1rem','borderRadius' : '2rem'}
                                                             )]),
                                 html.Div([dbc.Input(id='db_user',
                                           type="text",
                                           debounce=True,
                                           min=-10000, max=10000, step=1,
                                           bs_size="mr",
                                           style={'width': '11rem', 'marginTop': '1.5rem', 'borderRadius' : '1rem'},
                                           autoFocus=True,
                                           placeholder="Enter your Username"),
                                         dbc.Input(id='db_password',
                                                   type="password",
                                                   debounce=True,
                                                   min=-10000, max=10000, step=1,
                                                   bs_size="mr",
                                                   style={'width': '11rem', 'marginTop': '1.5rem','borderRadius' : '1rem'},
                                                   autoFocus=True,
                                                   placeholder="Enter your password"),], className = 'ab'),

                                ], className='page2design1'),
                   html.Div([
                       dcc.Dropdown(id='db_name',
                                    options=[{'label': i, 'value': i}
                                             for i in ['rcckn', 'enerbat']],
                                    multi=False,
                                    style={'cursor': 'pointer', 'marginTop': '5px','borderRadius' : '1rem'},
                                    className='stockSelectorClass3',
                                    clearable=True,
                                    placeholder='Select Database',

                                    ),
                       dcc.Dropdown(id='dbvalchoosen',
                                    # options=[{'label': i, 'value': i}
                                    #          for i in df.columns],
                                    multi=False,
                                    style={'cursor': 'pointer', 'marginTop': '5px','borderRadius' : '1rem'},
                                    className='stockSelectorClass3',
                                    clearable=True,
                                    placeholder='Select Table ...',

                                    ),

                       dcc.Dropdown(id='dbvalname',
                                    # options=[{'label': i, 'value': i}
                                    #          for i in df.columns],
                                    multi=True,
                                    style={'cursor': 'pointer', 'marginTop': '13px','borderRadius' : '1rem'},
                                    className='stockSelectorClass3',
                                    clearable=True,
                                    placeholder='Select your parameters...',
                                    ),

                       dcc.Dropdown(id='dbvaldate',
                                    # options=[{'label': i, 'value': i}
                                    #          for i in df.columns],
                                    multi=True,
                                    style={'cursor': 'pointer', 'marginTop': '13px','borderRadius' : '1rem'},
                                    className='stockSelectorClass3',
                                    clearable=False,
                                    placeholder='Select your time...',
                                    ), ], className='aadb'),
                   html.Div([
                            daq.BooleanSwitch(
                                  id="calculintegraldb",
                                  on=False,
                                  label="Calculate Integral",
                                  color= '#1f78b4',
                                  labelPosition="bottom",
                                  style = {'margin': '5rem'}
                            )
                        ])

                ], className='abcdb'),
     dcc.Store(id='memory-output'),
     html.Div(id='dbcheck', children=
     [html.Div([html.Div([dcc.Dropdown(id='firstChoosenValuedb',
                                       options=[{'label': i, 'value': i} for i in
                                                []],
                                       multi=False,
                                       style={'cursor': 'pointer', 'width': '180px'},

                                       clearable=True,
                                       placeholder='First Value...',
                                       ),
                          dbc.Input(id='leftIntegralFirstdb',
                                    type="text",
                                    debounce=True,
                                    min=-10000, max=10000, step=1,
                                    bs_size="sm",
                                    style={'width': '8rem', 'marginTop': '1.5rem'},
                                    autoFocus=True,
                                    placeholder="first point"),
                          dbc.Input(id='leftIntegralSeconddb',
                                    type="text",
                                    debounce=True,
                                    min=-10000, max=10000, step=1,
                                    bs_size="sm",
                                    style={'width': '8rem', 'marginTop': '1.5rem'},
                                    autoFocus=True,
                                    placeholder="second point"),
                          dbc.Input(id='leftIntegraldb',
                                    type="text",
                                    min=-10000, max=10000, step=1,
                                    bs_size="sm",
                                    style={'width': '9rem', 'marginTop': '1.5rem'},
                                    autoFocus=True,
                                    placeholder="total integration"),
                          ]), html.Div([html.Button("Save", id="write_exceldb", n_clicks=0,
                                                    style={'fontSize': '1rem', 'width': '4rem',
                                                           'margin': '1rem'},
                                                    ),
                                        html.A(html.Button("Download Data",
                                                           id='download_datadb',
                                                           n_clicks=0,
                                                           style={'fontSize': '1rem',
                                                                  'width': '9rem',
                                                                  'margin': '1rem'}, ),
                                               id='download_exceldb',
                                               # # download="rawdata.csv",
                                               href="/download_exceldb/",
                                               # target="_blank"
                                               ),
                                        ], className='ad')

                ]),
      html.Div([dbc.Checklist(
          id='operateurdb',
          options=[{'label': i, 'value': i} for i in
                   ['Plus', 'Moins', 'Multiplie', 'Division']],
          value=[],
          labelStyle={'display': 'Block'},
      ), ]),
      html.Div([
          dcc.Dropdown(id='secondChoosenValuedb',
                       options=[{'label': i, 'value': i} for i in
                                []],
                       multi=False,
                       style={'cursor': 'pointer', 'width': '180px'},

                       clearable=True,
                       placeholder='Second Value...',
                       ),
          dbc.Input(id='rightIntegralFirstdb',
                    type="text",
                    min=-10000, max=10000, step=1,
                    bs_size="sm",
                    style={'width': '8rem', 'marginTop': '1.5rem'},
                    autoFocus=True,
                    placeholder="first point"),
          dbc.Input(id='rightIntegralSeconddb',
                    type="text",
                    min=-10000, max=10000, step=1,
                    bs_size="sm",
                    style={'width': '8rem', 'marginTop': '1.5rem'},
                    autoFocus=True,
                    placeholder="second point"),
          dbc.Input(id='rightIntegraldb',
                    type="text",
                    min=-10000, max=10000, step=1,
                    bs_size="sm",
                    style={'width': '9rem', 'marginTop': '1.5rem'},
                    autoFocus=True,
                    placeholder="total integration")
      ]),
      html.Div([dbc.Input(id='operationdb',
                          type="text",
                          min=-10000, max=10000, step=1,
                          bs_size="sm",
                          style={'width': '10rem', 'marginTop': '2rem',
                                 'height': '5rem', 'textAlign': 'center'},
                          autoFocus=True,
                          placeholder="result"),
                dbc.Input(id='intersectiondb',
                          type="text",
                          min=-10000, max=10000, step=1,
                          bs_size="sm",
                          style={'width': '10rem', 'marginTop': '2rem',
                                 'height': '2rem', 'textAlign': 'center'},
                          autoFocus=True,
                          placeholder="Intersection")], className='aa')
      ], style={'display': 'None'},
              className='abdbase'),
     html.Div([html.Div([html.Div([html.Div(dcc.RadioItems(id="radiographdb",
                               options=[
                                   {'label': 'Point', 'value': 'markers'},
                                   {'label': 'Line', 'value': 'lines'},
                                   {'label': 'Line + Point', 'value': 'lines+markers'}],
                               value='markers',
                               labelClassName='groupgraph2',
                               labelStyle={'margin': '10px'},
                               inputStyle={'margin': '10px'}
                               ), className='abdbside-db'),
                        html.Div([dcc.Dropdown(id="dropadddb",
                                                       options=[
                                                           {'label': 'Note', 'value': 'note'},
                                                           {'label': 'Header', 'value': 'header'},
                                                           {'label': 'x-axis', 'value': 'x_axis'},
                                                           {'label': 'y-axis', 'value': 'y_axis'},
                                                           {'label': 'y2-axis', 'value': 'y2_axis'},
                                                           {'label': 'y3-axis', 'value': 'y3_axis'},],
                                                       value='header',
                                                       ),
                                          dcc.Textarea(
                                              id='textareadb',
                                              value='',
                                              style={'width': '15rem', 'marginTop': '0.5rem'},
                                          ),
                                          dbc.Button("Add Text", id='addTextdb', n_clicks=0,
                                                                   className='mr-1', color="primary", style={'margin': '1rem 1rem 0 6vw'}),

                                          dcc.Dropdown(id='characteredb',
                                                    options=[{'label': i, 'value': i} for i in [8,12,14,16,18,20,22,24,26,28]],
                                                    value = 16,
                                                    multi=False,
                                                    style={'cursor': 'pointer', 'width': '120px', 'margin': '1rem'},
                                                    clearable=True,
                                                    placeholder='Charactere...',
                                                    ),
                                          ], className='aatabdb'),], className='abpagedb'),

               html.Div([html.Div([
                         html.Div(dcc.Loading(type='cube',children = dcc.Graph(id="getdbgraph",
                                            config={'displayModeBar': True,
                                                    'scrollZoom': True,
                                                    'displaylogo': False,
                                                    'modeBarButtonsToAdd': [
                                                        'drawline',
                                                        'drawrect',
                                                        'drawopenpath',
                                                        'select2d',
                                                        'eraseshape',

                                                    ]},
                                            style={'marginTop': '20px', },
                                            figure={
                                                'layout': {'legend': {'tracegroupgap': 0},

                                                           }
                                            }

                                            ), ),),
                                        html.Div([daq.BooleanSwitch(
                                                             id="selectyaxisdb",
                                                             label="Multiple Y-axis",
                                                             labelPosition="bottom",
                                                             color='red',

                                                         )
                                                             ,
                                                             dbc.Tooltip(
                                                                 "You can select maximum 3 y-axis",
                                                                 target="selectyaxisdb",
                                                                 placement='bottom',
                                                             ),
                                                         ], className='pluraly'),
                         html.Div(daq.Slider(id="sliderHeightdb",
                                             max=2100,
                                             min=400,
                                             value=530,
                                             step=100,
                                             size=400,
                                             vertical=True,
                                             updatemode='drag'), style={'margin': '20px'})], className='abcdb_graph'),

               html.Div([daq.Slider(id="sliderWidthdb",
                                             max=2000,
                                             min=600,
                                             value=1000,
                                             step=100,
                                             size=600,

                                             updatemode='drag')],className='design_page1'),
                         ],className='design_page2'),],className='acsecond'),
               html.Div(dash_table.DataTable(id="getdbtable",
                                             editable=True,
                                             page_size=50,
                                             style_table={'height': '500px', 'overflowY': 'auto', 'width': '98%'},
                                             style_cell={
                                                 'overflow': 'hidden',
                                                 'textOverflow': 'ellipsis',
                                                 'maxWidth': 0,
                                                 'fontSize': '1rem',
                                                 'TextAlign': 'center',
                                             },

                                             fixed_rows={'headers': True},
                                             style_header={
                                                 'backgroundColor': 'rgb(230, 230, 230)',
                                                 'fontWeight': 'bold'
                                             },
                                             filter_action="native",
                                             sort_action="native",
                                             sort_mode="multi",
                                             column_selectable="single",
                                             selected_columns=[],
                                             selected_rows=[],
                                             page_action="native",
                                             page_current=0,
                                             export_format='xlsx',
                                             export_headers='display',
                                             merge_duplicate_headers=True),style = {'width': '80%', 'margin': 'auto'}),
               html.Div(id='pointLeftFirstdb', children=[], style={'display': 'None'}),
               html.Div(id='pointLeftSeconddb', children=[], style={'display': 'None'}),
               html.Div(id='pointRightFirstdb', children=[], style={'display': 'None'}),
               html.Div(id='pointRightSeconddb', children=[], style={'display': 'None'}),
               html.Div(id='hiddenrecord1db', children=[], style={'display': 'None'}),
               html.Div(id='hiddenrecord3db', children=[], style={'display': 'None'}),
               html.Div(id='hiddenrecord4db', children=[], style={'display': 'None'}),
               html.Div(id='writeexcelhiddendb', children=[], style={'display': 'None'}),
               html.Div(id='hiddenTextHeaderdb', children=[], style={'display': 'None'}),
               html.Div(id='hiddenTextNotedb', children=[], style={'display': 'None'}),
               html.Div(id='hiddenTextxaxisdb', children=[], style={'display': 'None'}),
               html.Div(id='hiddenTextyaxisdb', children=[], style={'display': 'None'}),
               html.Div(id='hiddenTexty1axisdb', children=[], style={'display': 'None'}),
               html.Div(id='hiddenTexty2axisdb', children=[], style={'display': 'None'}),

               ],className='four-columns-div-user-controlsreel' ), ], ),

page_3_layout = html.Div([html.Div([
                            html.Div([html.Div([html.Div([
                                                          html.Div([html.Div([html.I(className="fas fa-home"), ]),
                                                                    dcc.Link('Home', href='/', id='link1')],
                                                                   className='icon_position3'),
                                                          html.Div([html.Div([html.I(className="far fa-file-excel"), ]),
                                                                    dcc.Link('Analysis', href='/File', id='link5')],
                                                                   className='icon_position3'),
                                                          html.Div([html.Div([html.I(className="fas fa-database"), ]),
                                                                    dcc.Link('Database', href='/Database', id='link2')],
                                                                   className='icon_position3'),
                                                          html.Div([html.Div([html.I(className="fas fa-chart-line"), ]),
                                                                    dcc.Link('RCC/KN', href='/RCC_KN',
                                                                             id='link4')], className='icon_position3'),
                                                          ],style = {'marginTop':'1rem'},className='ab-page-3'),
                                                daq.PowerButton(id='my-toggle-switch-reel',
                                                                       label={'label': 'Connection',
                                                                              'style': {'fontSize': '22px', 'fontWeight': 'bold',},},
                                                                       labelPosition='bottom', on=False, size=100, color="green",style = {'margin':'3rem 0'},
                                                                       className='dark-theme-control'),]),
                                               dcc.Store(id='get_data_from_modbus'),
                                               html.Div(id='data_to_store_id', children=[], style={'display': 'None'}),
                                               html.Div(id='data_to_store_value', children=[], style={'display': 'None'}),
                                               html.Div(id='data_to_store_qualite', children=[], style={'display': 'None'}),
                                               html.Div(id='data_to_store_date', children=[], style={'display': 'None'}),
                                               dcc.Interval(
                                                   id='interval_component',
                                                   disabled=True,
                                                   interval=1 * 1000,  # in milliseconds
                                                   n_intervals=0),
                            html.Div([
                                     dcc.Dropdown(id='realvalue',
                                                       multi=True,
                                                       style={'cursor': 'pointer'},
                                                       className='stockSelectorClassPage3',
                                                       clearable=True,
                                                       placeholder='Select Value',
                                                       ),
                                          html.Div([html.P('Enter interval value (Second)', style={'margin':'1em 2em 2em 5em'}),
                                                  dbc.Input(id='interval_value', type="text", value='5',
                                                            min=0, max=1000000000, step=1, bs_size="lg", style={'width': '6rem', 'margin':'1em'}, ),], className='acsecond'),

                                      html.Div([
                                                html.Div(
                                                    [
                                                        dbc.Button("Send Values to Database", id='download_reel_db', n_clicks=0, size="lg",
                                                                   className='mr-1', color="primary", style={'margin': '-3rem 1rem 0 6vw'}),
                                                        dbc.Modal(
                                                            [
                                                                dbc.ModalHeader("Save Your Table In Database"),
                                                                dbc.Input(id='input_user_real',
                                                                          type="text",
                                                                          min=-10000, max=10000, step=1, bs_size="sm",
                                                                          style={'width': '31rem', },
                                                                          placeholder='Enter Username',
                                                                          autoFocus=True, ),
                                                                dbc.Input(id='input_pswrd_real',
                                                                          type="password",
                                                                          min=-10000, max=10000, step=1, bs_size="sm",
                                                                          style={'width': '31rem', },
                                                                          placeholder='Enter Password',
                                                                          autoFocus=True, ),
                                                                dbc.Input(id='input_databasename',
                                                                          type="text",
                                                                          min=-10000, max=10000, step=1, bs_size="sm",
                                                                          style={'width': '31rem', },
                                                                          placeholder = 'Enter Database name',
                                                                          autoFocus=True, ),
                                                                dbc.Input(id='input_tablename',
                                                                          type="text",
                                                                          min=-10000, max=10000, step=1, bs_size="sm",
                                                                          style={'width': '31rem', },
                                                                          placeholder = 'Enter Table name',
                                                                          autoFocus=True, ),
                                                                dbc.ModalFooter([
                                                                    dbc.Button("Okey", id="ok_reel", className='ml-auto'),
                                                                    dbc.Button("Close", id="close_reel", className='ml-auto')]
                                                                ),
                                                            ],
                                                            id="modal_reel",
                                                        ), ]),

                                                ],style = {'margin':'3rem'}, className='abcd'),

                                      ]),html.Div([html.Div([html.Div([daq.Knob(id='HVA1IN',color='blue',label={"label": "HV A1 IN", "style": {'color': 'blue','marginBottom':'-1rem'}},
                                                                                value=0,size= 150,max=100, labelPosition = 'top'),
                                                                      daq.LEDDisplay(id = 'HVA1INLED',value = 0, color= 'blue', size=30,style = {'margin':'-2rem 0 2rem 0'})],
                                                                      className = 'aadbknob'),
                                                             html.Div([daq.Knob(id='HVA2IN',color='blue', label={"label": "HV A2 IN", "style": {'color': 'blue','marginBottom':'-1rem'}},
                                                                                value=0,size=150, max=100, labelPosition='top'),
                                                                       daq.LEDDisplay(id='HVA2INLED', value = 0, color='blue', size=30, style={'margin': '-2rem 0 2rem 0'})],
                                                                      className='aadbknob'),], className = 'abc'),
                                        html.Div([
                                                html.Div(
                                                    [
                                                        dbc.Button("Send Valve Values to Server", id='download_reel_valve', n_clicks=0, size="lg",
                                                                   className='mr-1', color="primary", style={'margin': '-3rem 1rem 0 6vw'}),
                                                        ]),

                                                ],style = {'margin':'3rem'}, className='abcd'),
                                                   html.Div([html.Div([daq.Knob(id='HVA1OUT',color='red', label={"label": "HV A1 OUT", "style": {'color': 'red','marginBottom':'-1rem'}},
                                                                                value=0,size= 150,max=100, labelPosition = 'top'),
                                                                      daq.LEDDisplay(id = 'HVA1OUTLED',value = 0, color= 'blue', size=30,style = {'margin':'-2rem 0 2rem 0'})],
                                                                      className = 'aadbknob'),
                                                             html.Div([daq.Knob(id='HVA2OUT',color='red',  label={"label": "HV A2 OUT", "style": {'color': 'red','marginBottom':'-1rem'}},
                                                                                value=0,size=150, max=100, labelPosition='top'),
                                                                       daq.LEDDisplay(id='HVA2OUTLED',value = 0, color='blue', size=30, style={'margin': '-2rem 0 2rem 0'})],
                                                                      className='aadbknob'), ], className = 'abc'),]),
                                                  ], className='acreel'),

              html.Div([html.Div([ dcc.Graph(id="graphreal",
                                                     config={'displayModeBar': True,
                                                             'scrollZoom': True,
                                                             'displaylogo': False,
                                                             'modeBarButtonsToAdd': [
                                                                 'drawline',
                                                                 'drawrect',
                                                                 'drawopenpath',
                                                                 'select2d',
                                                                 'eraseshape',
                                                             ]},
                                                     style={'marginTop': '20px', },
                                                     figure={
                                                         'layout': {'legend': {'tracegroupgap': 0},

                                                                    }
                                                     }
                                                     ),
                                  daq.Slider(id="sliderHeightreel",
                                                      max=2100,
                                                      min=400,
                                                      value=530,
                                                      step=100,
                                                      size=400,
                                                      vertical=True,
                                                      updatemode='drag'), ],style={'marginTop': '3rem'},className='abcdb_graph2'),
                        html.Div([html.Div(daq.Slider(id="sliderWidthreel",
                                                      max=2000,
                                                      min=600,
                                                      value=1000,
                                                      step=100,
                                                      size=600,
                                                      updatemode='drag'), style={'marginLeft': '2rem'}),
                                  ]),
                        html.Div(dash_table.DataTable(id="getrealtable",
                                                      editable=True,
                                                      page_size=50,
                                                      style_table={'height': '500px', 'overflowY': 'auto',
                                                                   'width': '60vw', 'margin': 'auto'},
                                                      style_cell={
                                                          'overflow': 'hidden',
                                                          'textOverflow': 'ellipsis',
                                                          'maxWidth': 0,
                                                          'fontSize': '1rem',
                                                          'TextAlign': 'center',
                                                      },

                                                      fixed_rows={'headers': True},
                                                      style_header={
                                                          'backgroundColor': 'rgb(230, 230, 230)',
                                                          'fontWeight': 'bold'
                                                      },
                                                      filter_action="native",
                                                      sort_action="native",
                                                      sort_mode="multi",
                                                      column_selectable="single",
                                                      selected_columns=[],
                                                      selected_rows=[],
                                                      page_action="native",
                                                      page_current=0,
                                                      export_format='xlsx',
                                                      export_headers='display',
                                                      merge_duplicate_headers=True))
                        ],className='four-columns-div-user-controlsreel'),
              html.Div(id='reelhidden1', children=[], style={'display': 'None'}),
              html.Div(id='reelhidden2', children=[], style={'display': 'None'}),
              html.Div(id='reelhidden3', children=[], style={'display': 'None'}),
              html.Div(id='reelhidden_user', children=[], style={'display': 'None'}),
              html.Div(id='reelhidden_pswrd', children=[], style={'display': 'None'}),
              html.Div(id='reelhidden4', children=[], style={'display': 'None'}),
              html.Div(id='reelhidden5', children=[], style={'display': 'None'}),
              dcc.Store(id='reelhidden6'),
              html.Div(id='reelhidden8', children=[], style={'display': 'None'}),
              html.Div(id='reelhidden9', children=[], style={'display': 'None'}),
              html.Div(id='reelhidden10', children=[], style={'display': 'None'}),],className='main_container',),
              ])

page_4_layout = html.Div([html.Div([html.Div([html.Div([html.Div([
                                                        html.Div([html.Div([html.I(className="fas fa-home"),], ),
                                                                  dcc.Link('Home', href='/', id='link1')], className='icon_position4'),
                                                        html.Div([html.Div([html.I(className="far fa-file-excel"),]),
                                                                  dcc.Link('Analysis', href='/File', id='link4')], className='icon_position4'),
                                                        html.Div([html.Div([html.I(className="fas fa-database"), ]),
                                                                  dcc.Link('Database', href='/Database', id='link2')], className='icon_position4'),
                                                        html.Div([html.Div([html.I(className="fas fa-server"), ]),
                                                                  dcc.Link('Enerbat', href='/realTime_Enerbat', id='link3')], className='icon_position4'),

                                                                                    ],
                                                        className = 'abcdbpr' ),

                                                        dbc.Modal(
                                                            [
                                                                dbc.ModalHeader("Enter your username and password for access Databases"),
                                                                dbc.Input(id='username_pr',
                                                                          type="text",
                                                                          min=-10000, max=10000, step=1, bs_size="sm",
                                                                          style={'width': '31rem', },
                                                                          placeholder = 'Username',
                                                                          autoFocus=True, ),
                                                                dbc.Input(id='password_pr',
                                                                          type="password",
                                                                          min=-10000, max=10000, step=1, bs_size="sm",
                                                                          style={'width': '31rem', },
                                                                          placeholder = 'Password',
                                                                          autoFocus=True, ),
                                                                dbc.ModalFooter([
                                                                    dbc.Button("Okey", id="ok_reel_pr", className='ml-auto'),
                                                                    dbc.Button("Close", id="close_reel_pr", className='ml-auto')]
                                                                ),
                                                            ],
                                                            id="modal_reel_pr",
                                                        ),

                                    html.Div([html.Div([html.Div([daq.PowerButton(id='my-toggle-switch-pr-db',
                                                                                  label={'label': 'Connection Database',
                                                                                         'style': {'fontSize': '22px',
                                                                                                   'fontWeight': 'bold'}},
                                                                                  labelPosition='bottom', on=False, size=100,
                                                                                  color="green",
                                                                                  className='dark-theme-control'),

                                                                                ], style={'marginLeft': '1rem'}),
                                                        html.Div([ dcc.Dropdown(id='prname',
                                                                                options=[{'label': i, 'value': i}
                                                                                         for i in ['rcckn', 'enerbat']],
                                                                                multi=False,
                                                                                style={'cursor': 'pointer', 'marginTop': '5px','borderRadius' : '0.5rem'},
                                                                                className='stockSelectorClass3',
                                                                                clearable=True,
                                                                                placeholder='Select Database',
                                                                                ),
                                                                   dcc.Dropdown(id='prvalchoosen',
                                                                                # options=[{'label': i, 'value': i}
                                                                                #          for i in df.columns],
                                                                                multi=False,
                                                                                style={'cursor': 'pointer', 'marginTop': '5px','borderRadius' : '0.5rem'},
                                                                                className='stockSelectorClass3',
                                                                                clearable=True,
                                                                                placeholder='Select Table...',
                                                                                ),
                                                                   dcc.Dropdown(id='prvalname',
                                                                                # options=[{'label': i, 'value': i}
                                                                                #          for i in df.columns],
                                                                                multi=True,
                                                                                style={'cursor': 'pointer','marginTop': '13px','borderRadius' : '0.5rem'},
                                                                                className='stockSelectorClass3',
                                                                                clearable=True,
                                                                                placeholder='Select your parameters...',
                                                                                ),
                                                                   dcc.Dropdown(id='prvaldate',
                                                                                # options=[{'label': i, 'value': i}
                                                                                #          for i in df.columns],
                                                                                multi=True,
                                                                                style={'cursor': 'pointer', 'marginTop': '13px','borderRadius' : '0.5rem'},
                                                                                className='stockSelectorClass3',
                                                                                clearable=False,
                                                                                placeholder='Select your time...',
                                                                                ),
                                                                   html.P('Enter interval value (Second)'),
                                                                    dcc.Interval(
                                                                                 id='interval_component_pr_db',
                                                                                 disabled=True,
                                                                                 interval=1 * 1000,  # in milliseconds
                                                                                 n_intervals=0),
                                                                   dbc.Input(id='interval_value_pr_db', type="text", value='10',
                                                                             min=0, max=1000000000, step=1, bs_size="lg", style={'width': '6rem','borderRadius' : '0.5rem'}, ),
                                                                               ], className='page4reel'),

                                                                ],className='abcdbpage4upleft'),

                                            html.Div([html.Div([
                                                                    html.Div([daq.PowerButton(id='my-toggle-switch-pr',
                                                                                     label={'label': "Conn. Enerbat",
                                                                                            'style': {'fontSize': '22px',
                                                                                                      'fontWeight': 'bold'}},
                                                                                     labelPosition='bottom', on=False, size=100,
                                                                                     color="green",
                                                                                     className='dark-theme-control'),
                                                                            dbc.Tooltip(
                                                                                    "!!! Before the connection, fulfill database and table name, "
                                                                                    "Then send to Database button",
                                                                                    target = "my-toggle-switch-pr",
                                                                                            ),
                                                                     ], className='abpower',style = {'margin':'0 1rem 0 5rem'}),
                                                                           dcc.Store(id='get_data_from_modbus_pr'),
                                                                           html.Div(id='data_to_store_id_pr', children=[], style={'display': 'None'}),
                                                                           html.Div(id='data_to_store_value_pr', children=[],
                                                                                    style={'display': 'None'}),
                                                                           html.Div(id='data_to_store_qualite_pr', children=[],
                                                                                    style={'display': 'None'}),
                                                                           html.Div(id='data_to_store_date_pr', children=[],
                                                                                    style={'display': 'None'}),
                                                                           dcc.Interval(
                                                                               id='interval_component_pr',
                                                                               disabled=True,
                                                                               interval=1 * 1000,  # in milliseconds
                                                                               n_intervals=0), ],className='page4reel'),
                                                            html.Div([
                                                                 dcc.Dropdown(id='realvalue_pr',
                                                                           options = [{'label': i[16:], 'value': i} for i in parameters_name],
                                                                           multi=True,
                                                                           style={'cursor': 'pointer', 'margin': '5px 5px 10px 0','borderRadius' : '0.5rem'
                                                                                  },
                                                                           className='stockSelectorClass3',
                                                                           clearable=True,
                                                                           placeholder='Select Value',

                                                                           ),
                                                              html.P('Enter interval value (Second)'),
                                                              dbc.Input(id='interval_value_pr', type="text", value='5',
                                                                        min=0, max=1000000000, step=1, bs_size="lg", style={'width': '6rem','borderRadius' : '0.5rem'} ),

                                                              html.Div(
                                                                        html.Div(
                                                                            [
                                                                                dbc.Button("Send to Database", id='download_pr',
                                                                                           n_clicks=0, size="lg",
                                                                                           className='mr-1', color="primary",
                                                                                           style={'margin': '1rem 1rem 1rem 0'}),
                                                                                dbc.Tooltip(
                                                                                    "!!! Enter a Database and Table name",
                                                                                    "If entered, disregard this message ",
                                                                                    target = "download_pr",
                                                                                            ),
                                                                                ]),
                                                                        className='abcd'),
                                                              html.Div([html.Div([html.P('Enter Table Name'),
                                                                                dbc.Input(id='filenametodb', type="text", value='',
                                                                                min=0, max=1000000000, step=1, bs_size="lg", style={'width': '10rem'}, ),]),
                                                                        html.Div([html.P('Enter Database Name', style={'marginLeft': '1rem', }),
                                                                                dbc.Input(id='nametodb', type="text", value='',
                                                                                min=0, max=1000000000, step=1, bs_size="lg",
                                                                                style={'width': '10rem', 'marginLeft': '1rem','borderRadius' : '0.5rem' }, ),])],className='abcd',),
                                                          ], className='page4reel', ),

                                  html.Div(id='reelhidden1pr', children=[], style={'display': 'None'}),
                                  html.Div(id='reelhidden2pr', children=[], style={'display': 'None'}),
                                  html.Div(id='reelhidden3pr', children=[], style={'display': 'None'}),
                                  html.Div(id='reelhidden4pr', children=[], style={'display': 'None'}),
                                  html.Div(id='reelhidden5pr', children=[], style={'display': 'None'}),
                                  html.Div(id='reelhidden6pr', children=[], style={'display': 'None'}),
                                  ],className='abcdbpage4upleft')
                                ],className='prstyle')
                                         ], className='page4reel'),
                               ], className='abcdbpage4'),
     dcc.Store(id='memory-outputpr'),
     html.Div([html.Div([html.Div([html.Div(dcc.Dropdown(id='firstgraph_pr_real',
                                            options=[{'label': i, 'value': i} for i in []],
                                            multi=True,
                                            style={'cursor': 'pointer', 'width': '30rem', 'margin' : '1rem 0 0 5rem'},
                                            clearable=True,
                                            placeholder='Values of Real Time',
                                                            ),),
                                html.Div(dcc.Dropdown(id='firstgraph_pr_db',
                                                options=[{'label': i, 'value': i} for i in []],
                                                multi=True,
                                                style={'cursor': 'pointer', 'width': '30rem', 'margin' : '1rem 0 0 5rem'},
                                                clearable=True,
                                                placeholder='Values of Database',
                                                            ),),
                       html.Div([html.Div([html.Div(dcc.Graph(id="getprgraph",
                                            config={'displayModeBar': True,
                                                    'scrollZoom': True,
                                                    'displaylogo': False,
                                                    'modeBarButtonsToAdd': [
                                                        'drawline',
                                                        'drawrect',
                                                        'drawopenpath',
                                                        'select2d',
                                                        'eraseshape',
                                                    ]},
                                            style={'marginTop': '20px', },
                                            figure={
                                                'layout': {'legend': {'tracegroupgap': 0},}
                                            }
                                            ), ),
                         html.Div(daq.Slider(id="sliderHeightpr",
                                             max=1200,
                                             min=200,
                                             value=400,
                                             step=100,
                                             size=300,
                                             vertical=True,
                                             updatemode='drag'), style={'margin': '2rem 2rem 0 1rem'})], style= {'margin' : '1rem 1rem 1rem 5rem'}, className='page4graph1'),
                        html.Div(daq.Slider(id="sliderWidthpr",
                                            max=1600,
                                            min=500,
                                            value=800,
                                            step=100,
                                            size=500,
                                                     updatemode='drag'), style={'marginLeft': '7rem'}),
                        ],style = {'margin':'1rem','padding':'10px'}, className='boxdesign1'),
                         ]),
                       html.Div(dcc.Dropdown(id='secondgraph_pr_real',
                                    options=[{'label': i, 'value': i} for i in []],
                                    multi=True,
                                    style={'cursor': 'pointer', 'width': '30rem','margin' : '3rem 0 0 5rem'},
                                    clearable=True,
                                    placeholder='Values of Real Time',
                               ),),
                               html.Div(dcc.Dropdown(id='secondgraph_pr_db',
                                    options=[{'label': i, 'value': i} for i in []],
                                    multi=True,
                                    style={'cursor': 'pointer', 'width': '30rem','margin' : '1rem 0 0 5rem'},
                                    clearable=True,
                                    placeholder='Values of Database',
                               ),),
                               html.Div([html.Div([html.Div(dcc.Graph(id="getprgraph2",
                                                    config={'displayModeBar': True,
                                                            'displaylogo': False,
                                                            'scrollZoom': True,
                                                            'modeBarButtonsToAdd': [
                                                                'drawline',
                                                                'drawrect',
                                                                'drawopenpath',
                                                                'select2d',
                                                                'eraseshape',
                                                            ]},
                                                    style={'marginTop': '20px' },
                                                    figure={
                                                        'layout': {'legend': {'tracegroupgap': 0},}
                                                    }
                                                    ), ),
                                                 html.Div(daq.Slider(id="sliderHeightpr2",
                                                                     max=1200,
                                                                     min=200,
                                                                     value=400,
                                                                     step=100,
                                                                     size=300,
                                                                     vertical=True,
                                                                     updatemode='drag'), style={'margin': '2rem 2rem 0 1rem'})],style = {'margin' : '1rem 1rem 1rem 5rem'}, className='page4graph1'),
                                                html.Div(daq.Slider(id="sliderWidthpr2",
                                                                    max=1600,
                                                                    min=500,
                                                                    value=800,
                                                                    step=100,
                                                                    size=500,
                                                                             updatemode='drag'), style={'marginLeft': '6rem'}),
                                                ],style = {'margin':'1rem','padding':'10px'}, className='boxdesign2'),
                                                 ]),

                html.Div([html.Div([html.Div([
                                html.Div([dcc.Dropdown(id='thirdgraph_pr_real',
                                                options=[{'label': i, 'value': i} for i in []],
                                                multi=True,
                                                style={'cursor': 'pointer', 'width': '30rem', 'margin' : '1rem 0 0 5rem'},
                                                clearable=True,
                                                placeholder='Values of Real Time',
                                                    ),
                                        dcc.Dropdown(id='thirdgraph_pr_db',
                                                options=[{'label': i, 'value': i} for i in []],
                                                multi=True,
                                                style={'cursor': 'pointer', 'width': '30rem', 'margin' : '1rem 0 0 5rem' },
                                                clearable=True,
                                                placeholder='Values of Database',
                                                )    ,], className = 'thirdgraphpr_db'),
                                       html.Div([html.Div([html.Div(dcc.Graph(id="getprgraph3",
                                                            config={'displayModeBar': True,
                                                                    'scrollZoom': True,
                                                                     'displaylogo': False,
                                                                    'modeBarButtonsToAdd': [
                                                                        'drawline',
                                                                        'drawrect',
                                                                        'drawopenpath',
                                                                        'select2d',
                                                                        'eraseshape',
                                                                    ]},
                                                            style={'marginTop': '20px', },
                                                            figure={
                                                                'layout': {'legend': {'tracegroupgap': 0},}
                                                            }
                                                            ), ),
                                         html.Div(daq.Slider(id="sliderHeightpr3",
                                                             max=1200,
                                                             min=200,
                                                             value=400,
                                                             step=100,
                                                             size=300,
                                                             vertical=True,
                                                             updatemode='drag'), style={'margin': '2rem 2rem 0 1rem'})],style = {'margin':'1rem 3rem 1rem 1rem'}, className='page4graph1'),
                                        html.Div(daq.Slider(id="sliderWidthpr3",
                                                            max=1600,
                                                            min=500,
                                                            value=800,
                                                            step=100,
                                                            size=500,
                                                                     updatemode='drag'), style={'marginLeft': '5rem'}),
                                        ],style = {'margin':'1rem','padding':'10px'}, className='boxdesign3'),
                                         ]),

                                       html.Div([html.Div(dcc.Dropdown(id='fourgraph_pr_real',
                                                                    options=[{'label': i, 'value': i} for i in []],
                                                                    multi=True,
                                                                    style={'cursor': 'pointer', 'width': '30rem', 'margin' : '3rem 0 0 5rem'},
                                                                    clearable=True,
                                                                    placeholder='Values of Real Time',
                                                                            ),),
                                               html.Div(dcc.Dropdown(id='fourgraph_pr_db',
                                                                options=[{'label': i, 'value': i} for i in []],
                                                                multi=True,
                                                                style={'cursor': 'pointer', 'width': '30rem', 'margin' : '1rem 0 0 5rem'},
                                                                clearable=True,
                                                                placeholder='Values of Database',
                                                                ),),], className = 'fourgraphpr_db'),
                                               html.Div([html.Div([html.Div(dcc.Graph(id="getprgraph4",
                                                                    config={'displayModeBar': True,
                                                                            'scrollZoom': True,
                                                                            'displaylogo': False,
                                                                            'modeBarButtonsToAdd': [
                                                                                'drawline',
                                                                                'drawrect',
                                                                                'drawopenpath',
                                                                                'select2d',
                                                                                'eraseshape',
                                                                            ]},
                                                                    style={'margin': '20px ' },
                                                                    figure={
                                                                        'layout': {'legend': {'tracegroupgap': 0},}
                                                                    }
                                                                    ), ),
                                                                 html.Div(daq.Slider(id="sliderHeightpr4",
                                                                                     max=1200,
                                                                                     min=200,
                                                                                     value=400,
                                                                                     step=100,
                                                                                     size=300,
                                                                                     vertical=True,
                                                                                     updatemode='drag'), style={'margin': '2rem 2rem 0 1rem'})],style = {'margin':'0 3rem 0 0'}, className='page4graph1'),
                                                                html.Div(daq.Slider(id="sliderWidthpr4",
                                                                                             max=1600,
                                                                                             min=500,
                                                                                             value=800,
                                                                                             step=100,
                                                                                             size=500,
                                                                                             updatemode='drag'), style={'marginLeft': '5rem'}),
                                                                ],style = {'margin':'1rem','padding':'10px'}, className='boxdesign4'),
                                                                 ], ), ]),], className='abcdbprGraph'),

               html.Div(dash_table.DataTable(id="getprtable",
                                             editable=True,
                                             page_size=50,
                                             style_table={'height': '500px', 'overflowY': 'auto', 'width': '98%'},
                                             style_cell={
                                                 'overflow': 'hidden',
                                                 'textOverflow': 'ellipsis',
                                                 'maxWidth': 0,
                                                 'fontSize': '1rem',
                                                 'TextAlign': 'center',
                                             },

                                             fixed_rows={'headers': True},
                                             style_header={
                                                 'backgroundColor': 'rgb(230, 230, 230)',
                                                 'fontWeight': 'bold' },
                                             filter_action="native",
                                             sort_action="native",
                                             sort_mode="multi",
                                             column_selectable="single",
                                             selected_columns=[],
                                             selected_rows=[],
                                             page_action="native",
                                             page_current=0,
                                             export_format='xlsx',
                                             export_headers='display',
                                             merge_duplicate_headers=True)),
               ], style = {'overflow-x' : 'auto'} ),])
